// chat_lang_flag.h
// Small flag next to the chat input line showing the current keyboard language.
// 46 languages are supported (Arabic -> Algeria, English -> United Kingdom, French -> France,
// Russian, Turkish, Ukrainian, Bulgarian, German, Spanish, ...).
// The flags are drawn from tiny pixel maps, so no image files are needed.
#pragma once

#include <cstddef>
#include <cstdint>
#include <cwchar>
#include <type_traits>
#include <utility>

// Keyboard layout detection on Windows:
//  - if windows.h is already included, GetKeyboardLayout is called directly;
//  - otherwise it is looked up in user32.dll at run time. Only two kernel32 functions are
//    declared by hand, windows.h is NOT included (it defines macros such as PostMessage
//    that break the rest of the client code).
#if defined(_WIN32) && defined(_WINDOWS_)
#define CHATLANG_HAS_WINAPI 1
#elif defined(_WIN32)
extern "C"
{
__declspec(dllimport) void *__stdcall GetModuleHandleA(const char *lpModuleName);
__declspec(dllimport) void *__stdcall GetProcAddress(void *hModule, const char *lpProcName);
}
#define CHATLANG_HAS_DYNAMIC_WINAPI 1
#endif

namespace ChatLang
{

// None = no flag. Any other value is 1 + the index of the flag in kFlags.
enum class Lang : int
{
	None = 0
};

constexpr int FLAG_W = 24;
constexpr int FLAG_H = 16;

// Colors: W white, K black, R red, G green, B navy, L blue, S sky blue, Y yellow, O orange, M maroon

// Arabic (Algeria)
static const char *const kFlag_ar[FLAG_H] = {
	"GGGGGGGGGGGGWWWWWWWWWWWW",
	"GGGGGGGGGGGGWWWWWWWWWWWW",
	"GGGGGGGGGGGGWWWWWWWWWWWW",
	"GGGGGGGGGGRRRRRRWWWWWWWW",
	"GGGGGGGGRRRGWWWWWWWWWWWW",
	"GGGGGGGGRRGGWWRWWWWWWWWW",
	"GGGGGGGRRRGGWWRWWWWWWWWW",
	"GGGGGGGRRRGGRRRRRWWWWWWW",
	"GGGGGGGRRRGGWRRRWWWWWWWW",
	"GGGGGGGRRRGGWRWRWWWWWWWW",
	"GGGGGGGGRRGGWWWWWWWWWWWW",
	"GGGGGGGGRRRGWWWWWWWWWWWW",
	"GGGGGGGGGGRRRRRRWWWWWWWW",
	"GGGGGGGGGGGGWWWWWWWWWWWW",
	"GGGGGGGGGGGGWWWWWWWWWWWW",
	"GGGGGGGGGGGGWWWWWWWWWWWW"
};

// Bulgarian
static const char *const kFlag_bg[FLAG_H] = {
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR"
};

// Chinese
static const char *const kFlag_zh[FLAG_H] = {
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRYYRRRRRRRRRRRR",
	"RRRRRYRRRRYYRRRRRRRRRRRR",
	"RRRRYYRRRRRRRRRRRRRRRRRR",
	"RRYYYYYYYRRRYYRRRRRRRRRR",
	"RRRYYYYRRRRRYYRRRRRRRRRR",
	"RRRYYYYRRRRRYYRRRRRRRRRR",
	"RRRYYRYRRRRRYYRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRYYRRRRRRRRRRRR",
	"RRRRRRRRRRYYRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR"
};

// Czech
static const char *const kFlag_cs[FLAG_H] = {
	"LWWWWWWWWWWWWWWWWWWWWWWW",
	"LLWWWWWWWWWWWWWWWWWWWWWW",
	"LLLLWWWWWWWWWWWWWWWWWWWW",
	"LLLLLWWWWWWWWWWWWWWWWWWW",
	"LLLLLLLWWWWWWWWWWWWWWWWW",
	"LLLLLLLLWWWWWWWWWWWWWWWW",
	"LLLLLLLLLLWWWWWWWWWWWWWW",
	"LLLLLLLLLLLWWWWWWWWWWWWW",
	"LLLLLLLLLLLRRRRRRRRRRRRR",
	"LLLLLLLLLLRRRRRRRRRRRRRR",
	"LLLLLLLLRRRRRRRRRRRRRRRR",
	"LLLLLLLRRRRRRRRRRRRRRRRR",
	"LLLLLRRRRRRRRRRRRRRRRRRR",
	"LLLLRRRRRRRRRRRRRRRRRRRR",
	"LLRRRRRRRRRRRRRRRRRRRRRR",
	"LRRRRRRRRRRRRRRRRRRRRRRR"
};

// Danish
static const char *const kFlag_da[FLAG_H] = {
	"RRRRRRRWWWRRRRRRRRRRRRRR",
	"RRRRRRRWWWRRRRRRRRRRRRRR",
	"RRRRRRRWWWRRRRRRRRRRRRRR",
	"RRRRRRRWWWRRRRRRRRRRRRRR",
	"RRRRRRRWWWRRRRRRRRRRRRRR",
	"RRRRRRRWWWRRRRRRRRRRRRRR",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"RRRRRRRWWWRRRRRRRRRRRRRR",
	"RRRRRRRWWWRRRRRRRRRRRRRR",
	"RRRRRRRWWWRRRRRRRRRRRRRR",
	"RRRRRRRWWWRRRRRRRRRRRRRR",
	"RRRRRRRWWWRRRRRRRRRRRRRR",
	"RRRRRRRWWWRRRRRRRRRRRRRR"
};

// German
static const char *const kFlag_de[FLAG_H] = {
	"KKKKKKKKKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKK",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY"
};

// Greek
static const char *const kFlag_el[FLAG_H] = {
	"LLLWWWLLLLLLLLLLLLLLLLLL",
	"LLLWWWLLLLLLLLLLLLLLLLLL",
	"LLLWWWLLLWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWLLLLLLLLLLLLLLL",
	"WWWWWWWWWLLLLLLLLLLLLLLL",
	"LLLWWWLLLWWWWWWWWWWWWWWW",
	"LLLWWWLLLWWWWWWWWWWWWWWW",
	"LLLWWWLLLLLLLLLLLLLLLLLL",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"LLLLLLLLLLLLLLLLLLLLLLLL"
};

// English (UK)
static const char *const kFlag_en[FLAG_H] = {
	"RRWWBBBBBBWRRWBBBBBBWWRR",
	"WRRWWBBBBBWRRWBBBBBWWRRW",
	"BWWRRWWBBBWRRWBBBWWRRWWB",
	"BBWWRRWWBBWRRWBBWWRRWWBB",
	"BBBBWWRRWWWRRWWWRRWWBBBB",
	"BBBBBWWRRWWRRWWRRWWBBBBB",
	"WWWWWWWWWWWRRWWWWWWWWWWW",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"WWWWWWWWWWWRRWWWWWWWWWWW",
	"BBBBBWWRRWWRRWWRRWWBBBBB",
	"BBBBWWRRWWWRRWWWRRWWBBBB",
	"BBWWRRWWBBWRRWBBWWRRWWBB",
	"BWWRRWWBBBWRRWBBBWWRRWWB",
	"WRRWWBBBBBWRRWBBBBBWWRRW",
	"RRWWBBBBBBWRRWBBBBBBWWRR"
};

// Spanish
static const char *const kFlag_es[FLAG_H] = {
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR"
};

// Finnish
static const char *const kFlag_fi[FLAG_H] = {
	"WWWWWWWLLLLWWWWWWWWWWWWW",
	"WWWWWWWLLLLWWWWWWWWWWWWW",
	"WWWWWWWLLLLWWWWWWWWWWWWW",
	"WWWWWWWLLLLWWWWWWWWWWWWW",
	"WWWWWWWLLLLWWWWWWWWWWWWW",
	"WWWWWWWLLLLWWWWWWWWWWWWW",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"WWWWWWWLLLLWWWWWWWWWWWWW",
	"WWWWWWWLLLLWWWWWWWWWWWWW",
	"WWWWWWWLLLLWWWWWWWWWWWWW",
	"WWWWWWWLLLLWWWWWWWWWWWWW",
	"WWWWWWWLLLLWWWWWWWWWWWWW",
	"WWWWWWWLLLLWWWWWWWWWWWWW"
};

// French
static const char *const kFlag_fr[FLAG_H] = {
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR",
	"BBBBBBBBWWWWWWWWRRRRRRRR"
};

// Hebrew (Israel)
static const char *const kFlag_he[FLAG_H] = {
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWLLWWWWWWWWWWW",
	"WWWWWWWWWLLWWLLWWWWWWWWW",
	"WWWWWWWWWLWWWWLWWWWWWWWW",
	"WWWWWWWWWLWWWWLWWWWWWWWW",
	"WWWWWWWWWLLWWLLWWWWWWWWW",
	"WWWWWWWWWWWLLWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW"
};

// Hungarian
static const char *const kFlag_hu[FLAG_H] = {
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG"
};

// Icelandic
static const char *const kFlag_is[FLAG_H] = {
	"LLLLLLWRRRWLLLLLLLLLLLLL",
	"LLLLLLWRRRWLLLLLLLLLLLLL",
	"LLLLLLWRRRWLLLLLLLLLLLLL",
	"LLLLLLWRRRWLLLLLLLLLLLLL",
	"LLLLLLWRRRWLLLLLLLLLLLLL",
	"WWWWWWWRRRWWWWWWWWWWWWWW",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"WWWWWWWRRRWWWWWWWWWWWWWW",
	"LLLLLLWRRRWLLLLLLLLLLLLL",
	"LLLLLLWRRRWLLLLLLLLLLLLL",
	"LLLLLLWRRRWLLLLLLLLLLLLL",
	"LLLLLLWRRRWLLLLLLLLLLLLL",
	"LLLLLLWRRRWLLLLLLLLLLLLL"
};

// Italian
static const char *const kFlag_it[FLAG_H] = {
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR",
	"GGGGGGGGWWWWWWWWRRRRRRRR"
};

// Japanese
static const char *const kFlag_ja[FLAG_H] = {
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWRRWWWWWWWWWWW",
	"WWWWWWWWWRRRRRRWWWWWWWWW",
	"WWWWWWWWRRRRRRRRWWWWWWWW",
	"WWWWWWWWRRRRRRRRWWWWWWWW",
	"WWWWWWWRRRRRRRRRRWWWWWWW",
	"WWWWWWWRRRRRRRRRRWWWWWWW",
	"WWWWWWWWRRRRRRRRWWWWWWWW",
	"WWWWWWWWRRRRRRRRWWWWWWWW",
	"WWWWWWWWWRRRRRRWWWWWWWWW",
	"WWWWWWWWWWWRRWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW"
};

// Korean
static const char *const kFlag_ko[FLAG_H] = {
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWKKKKWWWWWWWWWWWWKKKKWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWKKKKWWWWWWWWWWWWKKKKWW",
	"WWWWWWWWWWRRRRWWWWWWWWWW",
	"WWKKKKWWWRRRRRRWWWKKKKWW",
	"WWWWWWWWRRRRLLLRWWWWWWWW",
	"WWWWWWWWRRRRLLLLWWWWWWWW",
	"WWWWWWWWRRRRLLLLWWWWWWWW",
	"WWWWWWWWLRRRLLLLWWWWWWWW",
	"WWKKKKWWWLLLLLLWWWKKKKWW",
	"WWWWWWWWWWLLLLWWWWWWWWWW",
	"WWKKKKWWWWWWWWWWWWKKKKWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWKKKKWWWWWWWWWWWWKKKKWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW"
};

// Dutch
static const char *const kFlag_nl[FLAG_H] = {
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL"
};

// Norwegian
static const char *const kFlag_no[FLAG_H] = {
	"RRRRRRWBBBWRRRRRRRRRRRRR",
	"RRRRRRWBBBWRRRRRRRRRRRRR",
	"RRRRRRWBBBWRRRRRRRRRRRRR",
	"RRRRRRWBBBWRRRRRRRRRRRRR",
	"RRRRRRWBBBWRRRRRRRRRRRRR",
	"WWWWWWWBBBWWWWWWWWWWWWWW",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"WWWWWWWBBBWWWWWWWWWWWWWW",
	"RRRRRRWBBBWRRRRRRRRRRRRR",
	"RRRRRRWBBBWRRRRRRRRRRRRR",
	"RRRRRRWBBBWRRRRRRRRRRRRR",
	"RRRRRRWBBBWRRRRRRRRRRRRR",
	"RRRRRRWBBBWRRRRRRRRRRRRR"
};

// Polish
static const char *const kFlag_pl[FLAG_H] = {
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR"
};

// Portuguese
static const char *const kFlag_pt[FLAG_H] = {
	"GGGGGGGGGGRRRRRRRRRRRRRR",
	"GGGGGGGGGGRRRRRRRRRRRRRR",
	"GGGGGGGGGGRRRRRRRRRRRRRR",
	"GGGGGGGGGGRRRRRRRRRRRRRR",
	"GGGGGGGGGGRRRRRRRRRRRRRR",
	"GGGGGGGGYYYYRRRRRRRRRRRR",
	"GGGGGGGYYRRYYRRRRRRRRRRR",
	"GGGGGGGYRRRRYRRRRRRRRRRR",
	"GGGGGGGYRRRRYRRRRRRRRRRR",
	"GGGGGGGYYRRYYRRRRRRRRRRR",
	"GGGGGGGGYYYYRRRRRRRRRRRR",
	"GGGGGGGGGGRRRRRRRRRRRRRR",
	"GGGGGGGGGGRRRRRRRRRRRRRR",
	"GGGGGGGGGGRRRRRRRRRRRRRR",
	"GGGGGGGGGGRRRRRRRRRRRRRR",
	"GGGGGGGGGGRRRRRRRRRRRRRR"
};

// Romanian
static const char *const kFlag_ro[FLAG_H] = {
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR",
	"BBBBBBBBYYYYYYYYRRRRRRRR"
};

// Russian
static const char *const kFlag_ru[FLAG_H] = {
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR"
};

// Croatian / Serbian / Bosnian
static const char *const kFlag_hr[FLAG_H] = {
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRWWRRRRRRRRRRR",
	"WWWWWWWWWRRWWRRWWWWWWWWW",
	"WWWWWWWWWWWRRWWWWWWWWWWW",
	"WWWWWWWWWWWRRWWWWWWWWWWW",
	"WWWWWWWWWRRWWRRWWWWWWWWW",
	"WWWWWWWWWRRWWRRWWWWWWWWW",
	"WWWWWWWWWWWRRWWWWWWWWWWW",
	"LLLLLLLLLWWRRWWLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL"
};

// Slovak
static const char *const kFlag_sk[FLAG_H] = {
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWRRRRRRWWWWWWWWWWWWWWW",
	"WWWRRWWRRWWWWWWWWWWWWWWW",
	"LLLRRWWRRLLLLLLLLLLLLLLL",
	"LLLRWWWWRLLLLLLLLLLLLLLL",
	"LLLRWWWWRLLLLLLLLLLLLLLL",
	"LLLRRWWRRLLLLLLLLLLLLLLL",
	"LLLRRWWRRLLLLLLLLLLLLLLL",
	"LLLRRRRRRLLLLLLLLLLLLLLL",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR"
};

// Albanian
static const char *const kFlag_sq[FLAG_H] = {
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRKRRKKRRRRKKRRKRRRRR",
	"RRRRRKKKKKRKKRKKKKKRRRRR",
	"RRRRRKKKKKKKKKKKKKRRRRRR",
	"RRRRRRKKKKKKKKKKKKRRRRRR",
	"RRRRRRKKKKKKKKKKKKRRRRRR",
	"RRRRRRRKKKKKKKKKRRRRRRRR",
	"RRRRRRRRRRKKKRRRRRRRRRRR",
	"RRRRRRRRRRRKKRRRRRRRRRRR",
	"RRRRRRRRRRRKKRRRRRRRRRRR",
	"RRRRRRRRRRKKKKRRRRRRRRRR",
	"RRRRRRRRRRKKKKRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR"
};

// Swedish
static const char *const kFlag_sv[FLAG_H] = {
	"LLLLLLLYYYLLLLLLLLLLLLLL",
	"LLLLLLLYYYLLLLLLLLLLLLLL",
	"LLLLLLLYYYLLLLLLLLLLLLLL",
	"LLLLLLLYYYLLLLLLLLLLLLLL",
	"LLLLLLLYYYLLLLLLLLLLLLLL",
	"LLLLLLLYYYLLLLLLLLLLLLLL",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"LLLLLLLYYYLLLLLLLLLLLLLL",
	"LLLLLLLYYYLLLLLLLLLLLLLL",
	"LLLLLLLYYYLLLLLLLLLLLLLL",
	"LLLLLLLYYYLLLLLLLLLLLLLL",
	"LLLLLLLYYYLLLLLLLLLLLLLL",
	"LLLLLLLYYYLLLLLLLLLLLLLL"
};

// Thai
static const char *const kFlag_th[FLAG_H] = {
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR"
};

// Turkish
static const char *const kFlag_tr[FLAG_H] = {
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRWWWWWRRRRRRRRRRRR",
	"RRRRRRWWWRRRRRRRRRRRRRRR",
	"RRRRRWWWRRRRRRRRRRRRRRRR",
	"RRRRRWWRRRRRRRWRRRRRRRRR",
	"RRRRRWWRRRRRRWWWWRRRRRRR",
	"RRRRRWWRRRRRRRWWRRRRRRRR",
	"RRRRRWWRRRRRRRRRRRRRRRRR",
	"RRRRRWWWRRRRRRRRRRRRRRRR",
	"RRRRRRWWWRRRRRRRRRRRRRRR",
	"RRRRRRRWWWWWRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR"
};

// Urdu (Pakistan)
static const char *const kFlag_ur[FLAG_H] = {
	"WWWWWWGGGGGGGGGGGGGGGGGG",
	"WWWWWWGGGGGGGGGGGGGGGGGG",
	"WWWWWWGGGGGGGGGGGGGGGGGG",
	"WWWWWWGGGGGGGGWGGGGGGGGG",
	"WWWWWWGGGGGGWWGGGGWGGGGG",
	"WWWWWWGGGGGWWGGGGWWGGGGG",
	"WWWWWWGGGGGWWGGGGGGGGGGG",
	"WWWWWWGGGGGWWGGGGGGGGGGG",
	"WWWWWWGGGGGWWGGGGGGGGGGG",
	"WWWWWWGGGGGWWGGGGGGGGGGG",
	"WWWWWWGGGGGWWWWGGGGGGGGG",
	"WWWWWWGGGGGGWWWWWWGGGGGG",
	"WWWWWWGGGGGGGGWWGGGGGGGG",
	"WWWWWWGGGGGGGGGGGGGGGGGG",
	"WWWWWWGGGGGGGGGGGGGGGGGG",
	"WWWWWWGGGGGGGGGGGGGGGGGG"
};

// Indonesian
static const char *const kFlag_id[FLAG_H] = {
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW"
};

// Ukrainian
static const char *const kFlag_uk[FLAG_H] = {
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY"
};

// Belarusian
static const char *const kFlag_be[FLAG_H] = {
	"WRWRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"WRWRRRRRRRRRRRRRRRRRRRRR",
	"WWWRRRRRRRRRRRRRRRRRRRRR",
	"WRWRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"WRWRRRRRRRRRRRRRRRRRRRRR",
	"WWWRRRRRRRRRRRRRRRRRRRRR",
	"WRWRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"WRWRRRRRRRRRRRRRRRRRRRRR",
	"WWWGGGGGGGGGGGGGGGGGGGGG",
	"WRWGGGGGGGGGGGGGGGGGGGGG",
	"RRRGGGGGGGGGGGGGGGGGGGGG",
	"WRWGGGGGGGGGGGGGGGGGGGGG",
	"WWWGGGGGGGGGGGGGGGGGGGGG"
};

// Slovenian
static const char *const kFlag_sl[FLAG_H] = {
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWRRRRRWWWWWWWWWWWWWWWW",
	"WWWLWWWLWWWWWWWWWWWWWWWW",
	"WWWLWWWLWWWWWWWWWWWWWWWW",
	"LLLLLWLLLLLLLLLLLLLLLLLL",
	"LLLLLWLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR"
};

// Estonian
static const char *const kFlag_et[FLAG_H] = {
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"LLLLLLLLLLLLLLLLLLLLLLLL",
	"KKKKKKKKKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKK",
	"KKKKKKKKKKKKKKKKKKKKKKKK",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW"
};

// Latvian
static const char *const kFlag_lv[FLAG_H] = {
	"MMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMM",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"MMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMM"
};

// Lithuanian
static const char *const kFlag_lt[FLAG_H] = {
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"YYYYYYYYYYYYYYYYYYYYYYYY",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR"
};

// Persian (Iran)
static const char *const kFlag_fa[FLAG_H] = {
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWRRWWWWWWWWWWW",
	"WWWWWWWWWWRRRRWWWWWWWWWW",
	"WWWWWWWWWWRRRRWWWWWWWWWW",
	"WWWWWWWWWWWRRWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR"
};

// Vietnamese
static const char *const kFlag_vi[FLAG_H] = {
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRYYRRRRRRRRRRR",
	"RRRRRRRRRRRYYRRRRRRRRRRR",
	"RRRRRRRRRRRYYRRRRRRRRRRR",
	"RRRRRRRRYYYYYYYYRRRRRRRR",
	"RRRRRRRRRYYYYYYRRRRRRRRR",
	"RRRRRRRRRRYYYYRRRRRRRRRR",
	"RRRRRRRRRYYYYYYRRRRRRRRR",
	"RRRRRRRRRYYRRYYRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR"
};

// Armenian
static const char *const kFlag_hy[FLAG_H] = {
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"BBBBBBBBBBBBBBBBBBBBBBBB",
	"OOOOOOOOOOOOOOOOOOOOOOOO",
	"OOOOOOOOOOOOOOOOOOOOOOOO",
	"OOOOOOOOOOOOOOOOOOOOOOOO",
	"OOOOOOOOOOOOOOOOOOOOOOOO",
	"OOOOOOOOOOOOOOOOOOOOOOOO"
};

// Azerbaijani
static const char *const kFlag_az[FLAG_H] = {
	"SSSSSSSSSSSSSSSSSSSSSSSS",
	"SSSSSSSSSSSSSSSSSSSSSSSS",
	"SSSSSSSSSSSSSSSSSSSSSSSS",
	"SSSSSSSSSSSSSSSSSSSSSSSS",
	"SSSSSSSSSSSSSSSSSSSSSSSS",
	"RRRRRRRRRWWRRRRRRRRRRRRR",
	"RRRRRRRRWWRRRRWRRRRRRRRR",
	"RRRRRRRRWWRRRWWWRRRRRRRR",
	"RRRRRRRRWWRRRRWRRRRRRRRR",
	"RRRRRRRRWWRRRWRRRRRRRRRR",
	"RRRRRRRRRWWRRRRRRRRRRRRR",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG"
};

// Georgian
static const char *const kFlag_ka[FLAG_H] = {
	"WWWWWWWWWWRRRRWWWWWWWWWW",
	"WWWWWWWWWWRRRRWWWWWWWWWW",
	"WWWWWRWWWWRRRRWWWWRWWWWW",
	"WWWWRRRWWWRRRRWWWRRRWWWW",
	"WWWWWRWWWWRRRRWWWWRWWWWW",
	"WWWWWWWWWWRRRRWWWWWWWWWW",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"WWWWWWWWWWRRRRWWWWWWWWWW",
	"WWWWWRWWWWRRRRWWWWRWWWWW",
	"WWWWRRRWWWRRRRWWWRRRWWWW",
	"WWWWWRWWWWRRRRWWWWRWWWWW",
	"WWWWWWWWWWRRRRWWWWWWWWWW",
	"WWWWWWWWWWRRRRWWWWWWWWWW"
};

// Hindi (India)
static const char *const kFlag_hi[FLAG_H] = {
	"OOOOOOOOOOOOOOOOOOOOOOOO",
	"OOOOOOOOOOOOOOOOOOOOOOOO",
	"OOOOOOOOOOOOOOOOOOOOOOOO",
	"OOOOOOOOOOOOOOOOOOOOOOOO",
	"OOOOOOOOOOOOOOOOOOOOOOOO",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWBBBBWWWWWWWWWW",
	"WWWWWWWWWWBWWBWWWWWWWWWW",
	"WWWWWWWWWWBWBBWWWWWWWWWW",
	"WWWWWWWWWWBBBBWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG"
};

// Malay (Malaysia)
static const char *const kFlag_ms[FLAG_H] = {
	"BBBBBBBBBBBBRRRRRRRRRRRR",
	"BBBBYYBBBBBBRRRRRRRRRRRR",
	"BBBYBBBBBBBBWWWWWWWWWWWW",
	"BBYYBBBYYYBBWWWWWWWWWWWW",
	"BBYYBBBBYYBBRRRRRRRRRRRR",
	"BBBYBBBBBBBBRRRRRRRRRRRR",
	"BBBBYYBBBBBBWWWWWWWWWWWW",
	"BBBBBBBBBBBBWWWWWWWWWWWW",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"RRRRRRRRRRRRRRRRRRRRRRRR",
	"WWWWWWWWWWWWWWWWWWWWWWWW",
	"WWWWWWWWWWWWWWWWWWWWWWWW"
};

// Kazakh
static const char *const kFlag_kk[FLAG_H] = {
	"SYSSSSSSSSSSSSSSSSSSSSSS",
	"SYSSSSSSSSSSSSSSSSSSSSSS",
	"SYSSSSSSSSSSSSSSSSSSSSSS",
	"SYSSSSSSSSYYYYSSSSSSSSSS",
	"SYSSSSSSSYYYYYYSSSSSSSSS",
	"SYSSSSSSSYYYYYYSSSSSSSSS",
	"SYSSSSSSSYYYYYYSSSSSSSSS",
	"SYSSSSSSSYYYYYYSSSSSSSSS",
	"SYSSSSSSSSYYYYSSSSSSSSSS",
	"SYSSSSSSSSSSSSSSSSSSSSSS",
	"SYSSSSSSSSSSSSSSSSSSSSSS",
	"SYSSSSSSYYYYYYYYSSSSSSSS",
	"SYSSSSSSSYYYYYYSSSSSSSSS",
	"SYSSSSSSSSSSSSSSSSSSSSSS",
	"SYSSSSSSSSSSSSSSSSSSSSSS",
	"SYSSSSSSSSSSSSSSSSSSSSSS"
};

// Bengali (Bangladesh)
static const char *const kFlag_bn[FLAG_H] = {
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGRRRGGGGGGGGGGGG",
	"GGGGGGGRRRRRRRGGGGGGGGGG",
	"GGGGGGRRRRRRRRRGGGGGGGGG",
	"GGGGGGRRRRRRRRRGGGGGGGGG",
	"GGGGGGRRRRRRRRRGGGGGGGGG",
	"GGGGGGRRRRRRRRRGGGGGGGGG",
	"GGGGGGRRRRRRRRRGGGGGGGGG",
	"GGGGGGRRRRRRRRRGGGGGGGGG",
	"GGGGGGGRRRRRRRGGGGGGGGGG",
	"GGGGGGGGGRRRGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG",
	"GGGGGGGGGGGGGGGGGGGGGGGG"
};

struct FlagDef
{
	const char *code;           // ISO 639-1 language code
	int winLang;                // Windows primary language id
	const char *const *rows;    // FLAG_H strings of FLAG_W characters
};

static const FlagDef kFlags[] = {
	{ "ar", 0x01, kFlag_ar },
	{ "bg", 0x02, kFlag_bg },
	{ "zh", 0x04, kFlag_zh },
	{ "cs", 0x05, kFlag_cs },
	{ "da", 0x06, kFlag_da },
	{ "de", 0x07, kFlag_de },
	{ "el", 0x08, kFlag_el },
	{ "en", 0x09, kFlag_en },
	{ "es", 0x0A, kFlag_es },
	{ "fi", 0x0B, kFlag_fi },
	{ "fr", 0x0C, kFlag_fr },
	{ "he", 0x0D, kFlag_he },
	{ "hu", 0x0E, kFlag_hu },
	{ "is", 0x0F, kFlag_is },
	{ "it", 0x10, kFlag_it },
	{ "ja", 0x11, kFlag_ja },
	{ "ko", 0x12, kFlag_ko },
	{ "nl", 0x13, kFlag_nl },
	{ "no", 0x14, kFlag_no },
	{ "pl", 0x15, kFlag_pl },
	{ "pt", 0x16, kFlag_pt },
	{ "ro", 0x18, kFlag_ro },
	{ "ru", 0x19, kFlag_ru },
	{ "hr", 0x1A, kFlag_hr },
	{ "sk", 0x1B, kFlag_sk },
	{ "sq", 0x1C, kFlag_sq },
	{ "sv", 0x1D, kFlag_sv },
	{ "th", 0x1E, kFlag_th },
	{ "tr", 0x1F, kFlag_tr },
	{ "ur", 0x20, kFlag_ur },
	{ "id", 0x21, kFlag_id },
	{ "uk", 0x22, kFlag_uk },
	{ "be", 0x23, kFlag_be },
	{ "sl", 0x24, kFlag_sl },
	{ "et", 0x25, kFlag_et },
	{ "lv", 0x26, kFlag_lv },
	{ "lt", 0x27, kFlag_lt },
	{ "fa", 0x29, kFlag_fa },
	{ "vi", 0x2A, kFlag_vi },
	{ "hy", 0x2B, kFlag_hy },
	{ "az", 0x2C, kFlag_az },
	{ "ka", 0x37, kFlag_ka },
	{ "hi", 0x39, kFlag_hi },
	{ "ms", 0x3E, kFlag_ms },
	{ "kk", 0x3F, kFlag_kk },
	{ "bn", 0x45, kFlag_bn }
};

constexpr int kFlagCount = (int)(sizeof(kFlags) / sizeof(kFlags[0]));

inline const char *const *GetFlag(Lang lang)
{
	const int i = (int)lang - 1;
	return (i >= 0 && i < kFlagCount) ? kFlags[i].rows : nullptr;
}

inline const char *GetFlagCode(Lang lang)
{
	const int i = (int)lang - 1;
	return (i >= 0 && i < kFlagCount) ? kFlags[i].code : "";
}

inline Lang FromWindowsLang(int primaryLang)
{
	for (int i = 0; i < kFlagCount; i++)
		if (kFlags[i].winLang == primaryLang)
			return (Lang)(i + 1);
	return Lang::None;
}

// "AR", "ar", "RU", "uk"... -> Lang
inline Lang ParseShortCode(const wchar_t *code)
{
	if (!code || !code[0] || !code[1])
		return Lang::None;

	char a = (code[0] >= L'A' && code[0] <= L'Z') ? (char)(code[0] - L'A' + L'a') : (char)code[0];
	char b = (code[1] >= L'A' && code[1] <= L'Z') ? (char)(code[1] - L'A' + L'a') : (char)code[1];

	// same flag as another code
	if (a == 'n' && (b == 'b' || b == 'n')) { a = 'n'; b = 'o'; } // Norwegian Bokmal / Nynorsk
	else if ((a == 's' && b == 'r') || (a == 'b' && b == 's')) { a = 'h'; b = 'r'; } // Serbian / Bosnian

	for (int i = 0; i < kFlagCount; i++)
		if (kFlags[i].code[0] == a && kFlags[i].code[1] == b)
			return (Lang)(i + 1);
	return Lang::None;
}

// Uses IInput::GetIMELanguageShortCode when this vgui2 version has it,
// otherwise it compiles to a function that simply reports "unknown".
template <class T>
auto QueryShortCode(T *pInput, wchar_t *buf, int bytes, int)
    -> decltype(pInput->GetIMELanguageShortCode(buf, bytes), bool())
{
	buf[0] = 0;
	pInput->GetIMELanguageShortCode(buf, bytes);
	return true;
}

template <class T>
bool QueryShortCode(T *, wchar_t *buf, int, long)
{
	buf[0] = 0;
	return false;
}

// Primary language id of the active keyboard layout, -1 when not available.
inline int WindowsLangId()
{
#if defined(CHATLANG_HAS_WINAPI)
	return (int)(((uintptr_t)GetKeyboardLayout(0)) & 0x3FF);
#elif defined(CHATLANG_HAS_DYNAMIC_WINAPI)
	typedef void *(__stdcall * GetKeyboardLayoutFn)(unsigned long);
	static GetKeyboardLayoutFn s_fn = nullptr;
	static bool s_tried = false;
	if (!s_tried)
	{
		s_tried = true;
		void *hUser32 = GetModuleHandleA("user32.dll");
		if (hUser32)
			s_fn = reinterpret_cast<GetKeyboardLayoutFn>(GetProcAddress(hUser32, "GetKeyboardLayout"));
	}
	if (!s_fn)
		return -1;
	return (int)(((uintptr_t)s_fn(0)) & 0x3FF);
#else
	return -1;
#endif
}

inline Lang DetectKeyboardLanguage()
{
	// 1) Windows keyboard layout
	const int win = WindowsLangId();
	if (win >= 0)
		return FromWindowsLang(win);

	// 2) vgui2 input method API
	wchar_t buf[16] = { 0 };
	QueryShortCode(vgui2::input(), buf, sizeof(buf), 0);
	return ParseShortCode(buf);
}

inline void PaletteColor(char c, int &r, int &g, int &b)
{
	switch (c)
	{
	case 'K': r = 0;   g = 0;   b = 0;   break;
	case 'R': r = 206; g = 17;  b = 38;  break;
	case 'G': r = 0;   g = 112; b = 58;  break;
	case 'B': r = 0;   g = 36;  b = 125; break;
	case 'L': r = 0;   g = 87;  b = 183; break;
	case 'S': r = 0;   g = 175; b = 202; break;
	case 'Y': r = 255; g = 205; b = 0;   break;
	case 'O': r = 255; g = 130; b = 0;   break;
	case 'M': r = 140; g = 21;  b = 21;  break;
	default:  r = 255; g = 255; b = 255; break; // 'W'
	}
}

} // namespace ChatLang

//-----------------------------------------------------------------------------
// Purpose: draws the flag of the current input language
//-----------------------------------------------------------------------------
class CChatLangFlag : public vgui2::Panel
{
	typedef vgui2::Panel BaseClass;

public:
	CChatLangFlag(vgui2::Panel *parent, const char *panelName)
	    : BaseClass(parent, panelName)
	{
		SetMouseInputEnabled(false);
		SetKeyBoardInputEnabled(false);
		SetPaintBackgroundEnabled(false);
		SetSize(ChatLang::FLAG_W + 2, ChatLang::FLAG_H + 2);
		SetVisible(false);
	}

	void SetLang(ChatLang::Lang lang) { m_Lang = lang; }
	ChatLang::Lang GetLang() const { return m_Lang; }

	virtual void Paint()
	{
		const char *const *flag = ChatLang::GetFlag(m_Lang);
		if (!flag)
			return;

		// dark outline so the flag is visible on any background
		vgui2::surface()->DrawSetColor(0, 0, 0, 200);
		vgui2::surface()->DrawFilledRect(0, 0, ChatLang::FLAG_W + 2, ChatLang::FLAG_H + 2);

		for (int y = 0; y < ChatLang::FLAG_H; y++)
		{
			const char *row = flag[y];
			int x = 0;
			while (x < ChatLang::FLAG_W)
			{
				// draw runs of the same color with one rectangle
				int end = x + 1;
				while (end < ChatLang::FLAG_W && row[end] == row[x])
					end++;

				int r, g, b;
				ChatLang::PaletteColor(row[x], r, g, b);
				vgui2::surface()->DrawSetColor(r, g, b, 255);
				vgui2::surface()->DrawFilledRect(1 + x, 1 + y, 1 + end, 2 + y);
				x = end;
			}
		}
	}

private:
	ChatLang::Lang m_Lang = ChatLang::Lang::None;
};
